name: Example Compute@Edge Workflow
on: [push]

defaults:
  run:
    working-directory: demo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Fastly CLI
      uses: ./setup
    - name: Install Dependencies
      run: npm install
    - name: Build Compute@Edge Package
      uses: ./build
      with:
        project_directory: demo
    - name: Deploy Compute@Edge Package
      uses: ./deploy
      with:
        project_directory: demo
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
